import type { Metadata } from "next";
import "./globals.css";

import { Bowlby_One, Inter } from "next/font/google";
import Navbar from "@/components/navbar/navbar";

const BowlbyOne = Bowlby_One({
    variable: "--font-bowlby",
    subsets: ["latin"],
    weight: ["400"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Convivial Futures",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} ${BowlbyOne.variable} antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
